name: prsum
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - bleach==1.5.0
  - click==7.1.2
  - fire==0.3.1
  - html5lib==0.9999999
  - importlib-metadata==1.6.1
  - joblib==0.15.1
  - markdown==3.2.2
  - nltk==3.5
  - numpy==1.16.0
  - protobuf==3.12.2
  - pyrouge==0.1.3
  - regex==2020.6.8
  - six==1.15.0
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.8
  - termcolor==1.1.0
  - torch==1.0.0
  - tqdm==4.46.1
  - werkzeug==1.0.1
  - zipp==3.1.0
